In [1]:
import re

In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
dataset = pd.read_csv("NLP_input.csv")


In [5]:
dataset

obj_type     accession accession_version  \
0     single nucleotide variant  VCV000706134     VCV000706134.   
1     single nucleotide variant  VCV000704207     VCV000704207.   
2     single nucleotide variant  VCV000702396     VCV000702396.   
3     single nucleotide variant  VCV000695193     VCV000695193.   
4                      Deletion  VCV000689700     VCV000689700.   
...                         ...           ...               ...   
1197  single nucleotide variant  VCV000007443     VCV000007443.   
1198  single nucleotide variant  VCV000007442     VCV000007442.   
1199                   Deletion  VCV000007441     VCV000007441.   
1200                   Deletion  VCV000007440     VCV000007440.   
1201  single nucleotide variant  VCV000007439     VCV000007439.   

                                title gene_sort  chr_sort  location_sort  \
0         NM_000455.5(STK11):c.327T>C     STK11        19        1218453   
1       NM_000455.5(STK11):c.863-7T>C     STK11        19        1221942   
2         NM_000455.5(STK11):c.684G>A     STK11        19        1220667   
3        NM_000455.5(STK11):c.1239T>C     STK11        19        1226584   
4     NM_000455.5(STK11):c.418_420del     STK11        19        1219365   
...                               ...       ...       ...            ...   
1197      NM_000455.4(STK11):c.250A>T     STK11        19        1207163   
1198    NM_000455.4(STK11):c.465-1G>A     STK11        19        1220372   
1199  NM_000455.4(STK11):c.718_721del     STK11        19        1220699   
1200      NM_000455.4(STK11):c.843del     STK11        19        1221321   
1201      NM_000455.4(STK11):c.759C>A     STK11        19        1221237   

     protein_change  fda_recognized_database  \
0               NaN                      NaN   
1               NaN                      NaN   
2               NaN                      NaN   
3               NaN                      NaN   
4           L140del                      NaN   
...             ...                      ...   
1197           K84*                      NaN   
1198            NaN                      NaN   
1199         S240fs                      NaN   
1200         L282fs                      NaN   
1201          Y253*                      NaN   

                                                    scv  \
0                        'SCV001019242', 'SCV001181020'   
1                                          SCV001016291   
2                        'SCV001013142', 'SCV001187970'   
3                                          SCV001000637   
4                        'SCV000992655', 'SCV001214728'   
...                                                 ...   
1197  'SCV000028074', 'SCV000889854', 'SCV000541165'...   
1198                                       SCV000028073   
1199                                       SCV000028072   
1200                                       SCV000028071   
1201                                       SCV000028070   

                                                 rcv             description  \
0                     'RCV000876645', 'RCV001019636'           Likely benign   
1                                       RCV000874158           Likely benign   
2                     'RCV000871473', 'RCV001025726'           Likely benign   
3                                       RCV000860553           Likely benign   
4                     'RCV000850457', 'RCV001050610'  Uncertain significance   
...                                              ...                     ...   
1197  'RCV000007869', 'RCV000132431', 'RCV000760079'              Pathogenic   
1198                                    RCV000007868              Pathogenic   
1199                                    RCV000007867              Pathogenic   
1200                                    RCV000007866              Pathogenic   
1201                                    RCV000007865              Pathogenic   

        last_evaluated                                    

In [6]:
dataset.fillna(value =0 )

obj_type     accession accession_version  \
0     single nucleotide variant  VCV000706134     VCV000706134.   
1     single nucleotide variant  VCV000704207     VCV000704207.   
2     single nucleotide variant  VCV000702396     VCV000702396.   
3     single nucleotide variant  VCV000695193     VCV000695193.   
4                      Deletion  VCV000689700     VCV000689700.   
...                         ...           ...               ...   
1197  single nucleotide variant  VCV000007443     VCV000007443.   
1198  single nucleotide variant  VCV000007442     VCV000007442.   
1199                   Deletion  VCV000007441     VCV000007441.   
1200                   Deletion  VCV000007440     VCV000007440.   
1201  single nucleotide variant  VCV000007439     VCV000007439.   

                                title gene_sort  chr_sort  location_sort  \
0         NM_000455.5(STK11):c.327T>C     STK11        19        1218453   
1       NM_000455.5(STK11):c.863-7T>C     STK11        19        1221942   
2         NM_000455.5(STK11):c.684G>A     STK11        19        1220667   
3        NM_000455.5(STK11):c.1239T>C     STK11        19        1226584   
4     NM_000455.5(STK11):c.418_420del     STK11        19        1219365   
...                               ...       ...       ...            ...   
1197      NM_000455.4(STK11):c.250A>T     STK11        19        1207163   
1198    NM_000455.4(STK11):c.465-1G>A     STK11        19        1220372   
1199  NM_000455.4(STK11):c.718_721del     STK11        19        1220699   
1200      NM_000455.4(STK11):c.843del     STK11        19        1221321   
1201      NM_000455.4(STK11):c.759C>A     STK11        19        1221237   

     protein_change  fda_recognized_database  \
0                 0                      0.0   
1                 0                      0.0   
2                 0                      0.0   
3                 0                      0.0   
4           L140del                      0.0   
...             ...                      ...   
1197           K84*                      0.0   
1198              0                      0.0   
1199         S240fs                      0.0   
1200         L282fs                      0.0   
1201          Y253*                      0.0   

                                                    scv  \
0                        'SCV001019242', 'SCV001181020'   
1                                          SCV001016291   
2                        'SCV001013142', 'SCV001187970'   
3                                          SCV001000637   
4                        'SCV000992655', 'SCV001214728'   
...                                                 ...   
1197  'SCV000028074', 'SCV000889854', 'SCV000541165'...   
1198                                       SCV000028073   
1199                                       SCV000028072   
1200                                       SCV000028071   
1201                                       SCV000028070   

                                                 rcv             description  \
0                     'RCV000876645', 'RCV001019636'           Likely benign   
1                                       RCV000874158           Likely benign   
2                     'RCV000871473', 'RCV001025726'           Likely benign   
3                                       RCV000860553           Likely benign   
4                     'RCV000850457', 'RCV001050610'  Uncertain significance   
...                                              ...                     ...   
1197  'RCV000007869', 'RCV000132431', 'RCV000760079'              Pathogenic   
1198                                    RCV000007868              Pathogenic   
1199                                    RCV000007867              Pathogenic   
1200                                    RCV000007866              Pathogenic   
1201                                    RCV000007865              Pathogenic   

        last_evaluated                                    

In [7]:
##dataset.loc['PVS1','ps1','PS2','PS3','PS4','PM1','PM2','PM3','PM4','PM5','PM6','PP1','PP2','PP3','PP4','PP5','BA1','BS1','BS2','BS3','BS4','BP1','BP2','BP3','BP4','BP5','BP6']

In [8]:
df =dataset.iloc[: ,37:64]


In [9]:
df

PVS1  PVS2  PS2  PS3  PS4  PM1  PM2  PM3  PM4  PM5  PM6  PP1  PP2  PP3  \
0      1.0   1.0  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1      NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2      NaN   NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3      NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
4      NaN   NaN  NaN  NaN  NaN  NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN  NaN   
...    ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1197   1.0   1.0  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN   
1198   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1199   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1200   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1201   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

      PP4  PP5  BA1  BS1  BS2  BS3  BS4  BP1  BP2  BP3  BP4  BP5  BP6  
0     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  
1     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
1197  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1198  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1199  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1200  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1201  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[1202 rows x 27 columns]

In [10]:
df =df.fillna(value = 0)

In [11]:
df


PVS1  PVS2  PS2  PS3  PS4  PM1  PM2  PM3  PM4  PM5  PM6  PP1  PP2  PP3  \
0      1.0   1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1      0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2      0.0   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3      0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4      0.0   0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
...    ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1197   1.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
1198   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1199   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1200   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1201   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      PP4  PP5  BA1  BS1  BS2  BS3  BS4  BP1  BP2  BP3  BP4  BP5  BP6  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
1197  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1198  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1199  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1201  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1202 rows x 27 columns]

In [12]:
Y = df.iloc[:,:].values

In [13]:
Y

array([[1., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
dataset['Description']

0       In silico models in agreement (benign);Synonym...
1                                                       -
2                                                       -
3                                                       -
4       This variant, c.418_420del, results in the del...
                              ...                        
1197    The p.K84* pathogenic mutation (also known as ...
1198                                                    -
1199                                                    -
1200                                                    -
1201                                                    -
Name: Description, Length: 1202, dtype: object

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1202 entries, 0 to 1201
Data columns (total 67 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   obj_type                     1202 non-null   object 
 1   accession                    1202 non-null   object 
 2   accession_version            1202 non-null   object 
 3   title                        1202 non-null   object 
 4   gene_sort                    1202 non-null   object 
 5   chr_sort                     1202 non-null   int64  
 6   location_sort                1202 non-null   int64  
 7   protein_change               571 non-null    object 
 8   fda_recognized_database      0 non-null      float64
 9   scv                          1202 non-null   object 
 10  rcv                          1202 non-null   object 
 11  description                  1202 non-null   object 
 12  last_evaluated               1202 non-null   object 
 13  review_status     

In [16]:
X_data =dataset['Description']


In [17]:
X_data

0       In silico models in agreement (benign);Synonym...
1                                                       -
2                                                       -
3                                                       -
4       This variant, c.418_420del, results in the del...
                              ...                        
1197    The p.K84* pathogenic mutation (also known as ...
1198                                                    -
1199                                                    -
1200                                                    -
1201                                                    -
Name: Description, Length: 1202, dtype: object

In [18]:
def decontraction(phrase):
    
    phrase = re.sub(r"won\'t", "will not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase =phrase.lower()
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    phrase = re.sub('\[.*?\]', ' ', phrase) 
    phrase = re.sub('https?://\S+|www\.\S+', ' ', phrase)
    phrase = re.sub('<.*?>+', ' ', phrase)
    phrase = re.sub('\n', ' ', phrase)
    phrase = re.sub('\w*\d\w*', ' ', phrase)
    return phrase

dataset.Description = [decontraction(word) for word in dataset.Description]

In [19]:
dataset.Description

0       in silico models in agreement (benign);synonym...
1                                                       -
2                                                       -
3                                                       -
4       this variant, c. , results in the deletion of ...
                              ...                        
1197    the p. * pathogenic mutation (also known as c....
1198                                                    -
1199                                                    -
1200                                                    -
1201                                                    -
Name: Description, Length: 1202, dtype: object

In [20]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer 
from nltk.stem import PorterStemmer
lemmatizer = WordNetLemmatizer()
ps = PorterStemmer()

In [21]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [22]:
corpus = []
for i in range(len(dataset.Description)):
    review = re.sub('[^a-zA-Z]' ,' ', dataset['Description'][i])
    review =review.lower()
    review = review.split()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    review = [lemmatizer.lemmatize(word) for word in review  if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)
print(corpus)

['silico model agreement benign synonymous alteration insufficient evidence classify benign', '', '', '', 'variant c result deletion amino acid protein p otherwise preserve integrity reading frame variant not present population database exac frequency variant not reported literature individual related condition experimental study prediction algorithm not available not evaluated variant functional significance affected amino acid currently unknown summary available evidence currently insufficient determine role variant disease therefore classified variant uncertain significance', 'variant considered likely benign benign based one following criterion conservative change occurs poorly conserved position protein predicted benign multiple silico algorithm population frequency not consistent disease', 'variant considered likely benign benign based one following criterion conservative change occurs poorly conserved position protein predicted benign multiple silico algorithm population frequen

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = TfidfVectorizer()
av = CountVectorizer()
X_des = cv.fit_transform(corpus).toarray()

In [24]:
X_des

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
len(X_des[0])


970

In [26]:
X_des[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.4711947 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.20128092, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [27]:
Y

array([[1., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
X_des

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
##import tensorflow as tf

In [30]:
##ann = tf.keras.models.Sequential()


In [31]:
##ann.add(tf.keras.layers.Dense(units = 10 , activation='relu'))


In [34]:

##ann.add(tf.keras.layers.Dense(units = 50 , activation='relu'))

##ann.add(tf.keras.layers.Dense(units =  , activation='relu'))

In [35]:

##ann.add(tf.keras.layers.Dense(units = 27 , activation='sigmoid'))

In [36]:

##ann.compile(optimizer = 'adam' , loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [37]:
##ann.fit(X_des , Y , batch_size = 10 , epochs = 10)


In [33]:
from sklearn import

SyntaxError: invalid syntax (<ipython-input-33-408eb292872b>, line 1)